<?php

namespace App\Constants\Shared;


class Countries{

    public const STATIC_COUNTRIES = 
    [
        'France',
        'United States',
        'Canada',
        'United Kingdom',
        'Germany',
        'Spain',
        'Italy',
        'Belgium',
        'Switzerland',
        'Luxembourg',
        'Netherlands',
        'Portugal',
        'Australia',
        'Japan',
        'China',
        'India',
        'Brazil',
        'Mexico',
        'Morocco',
        'Russia',
        'South Africa',
    ];


    public const STATIC_COUNTRY_CODES = 
    [
        // English names => Code
        'Afghanistan' => 'AF',
        'Albania' => 'AL',
        'Algeria' => 'DZ',
        'American Samoa' => 'AS',
        'Andorra' => 'AD',
        'Angola' => 'AO',
        'Anguilla' => 'AI',
        'Antarctica' => 'AQ',
        'Antigua and Barbuda' => 'AG',
        'Argentina' => 'AR',
        'Armenia' => 'AM',
        'Aruba' => 'AW',
        'Australia' => 'AU',
        'Austria' => 'AT',
        'Azerbaijan' => 'AZ',
        'Bahamas' => 'BS',
        'Bahrain' => 'BH',
        'Bangladesh' => 'BD',
        'Barbados' => 'BB',
        'Belarus' => 'BY',
        'Belgium' => 'BE',
        'Belize' => 'BZ',
        'Benin' => 'BJ',
        'Bermuda' => 'BM',
        'Bhutan' => 'BT',
        'Bolivia' => 'BO',
        'Bosnia and Herzegovina' => 'BA',
        'Botswana' => 'BW',
        'Brazil' => 'BR',
        'British Indian Ocean Territory' => 'IO',
        'British Virgin Islands' => 'VG',
        'Brunei' => 'BN',
        'Bulgaria' => 'BG',
        'Burkina Faso' => 'BF',
        'Burundi' => 'BI',
        'Cambodia' => 'KH',
        'Cameroon' => 'CM',
        'Canada' => 'CA',
        'Cape Verde' => 'CV',
        'Cayman Islands' => 'KY',
        'Central African Republic' => 'CF',
        'Chad' => 'TD',
        'Chile' => 'CL',
        'China' => 'CN',
        'Christmas Island' => 'CX',
        'Cocos Islands' => 'CC',
        'Colombia' => 'CO',
        'Comoros' => 'KM',
        'Cook Islands' => 'CK',
        'Costa Rica' => 'CR',
        'Croatia' => 'HR',
        'Cuba' => 'CU',
        'Curacao' => 'CW',
        'Cyprus' => 'CY',
        'Czech Republic' => 'CZ',
        'Democratic Republic of the Congo' => 'CD',
        'Denmark' => 'DK',
        'Djibouti' => 'DJ',
        'Dominica' => 'DM',
        'Dominican Republic' => 'DO',
        'East Timor' => 'TL',
        'Ecuador' => 'EC',
        'Egypt' => 'EG',
        'El Salvador' => 'SV',
        'Equatorial Guinea' => 'GQ',
        'Eritrea' => 'ER',
        'Estonia' => 'EE',
        'Ethiopia' => 'ET',
        'Falkland Islands' => 'FK',
        'Faroe Islands' => 'FO',
        'Fiji' => 'FJ',
        'Finland' => 'FI',
        'France' => 'FR',
        'French Polynesia' => 'PF',
        'Gabon' => 'GA',
        'Gambia' => 'GM',
        'Georgia' => 'GE',
        'Germany' => 'DE',
        'Ghana' => 'GH',
        'Gibraltar' => 'GI',
        'Greece' => 'GR',
        'Greenland' => 'GL',
        'Grenada' => 'GD',
        'Guam' => 'GU',
        'Guatemala' => 'GT',
        'Guernsey' => 'GG',
        'Guinea' => 'GN',
        'Guinea-Bissau' => 'GW',
        'Guyana' => 'GY',
        'Haiti' => 'HT',
        'Honduras' => 'HN',
        'Hong Kong' => 'HK',
        'Hungary' => 'HU',
        'Iceland' => 'IS',
        'India' => 'IN',
        'Indonesia' => 'ID',
        'Iran' => 'IR',
        'Iraq' => 'IQ',
        'Ireland' => 'IE',
        'Isle of Man' => 'IM',
        'Israel' => 'IL',
        'Italy' => 'IT',
        'Ivory Coast' => 'CI',
        'Jamaica' => 'JM',
        'Japan' => 'JP',
        'Jersey' => 'JE',
        'Jordan' => 'JO',
        'Kazakhstan' => 'KZ',
        'Kenya' => 'KE',
        'Kiribati' => 'KI',
        'Kosovo' => 'XK',
        'Kuwait' => 'KW',
        'Kyrgyzstan' => 'KG',
        'Laos' => 'LA',
        'Latvia' => 'LV',
        'Lebanon' => 'LB',
        'Lesotho' => 'LS',
        'Liberia' => 'LR',
        'Libya' => 'LY',
        'Liechtenstein' => 'LI',
        'Lithuania' => 'LT',
        'Luxembourg' => 'LU',
        'Macau' => 'MO',
        'Macedonia' => 'MK',
        'Madagascar' => 'MG',
        'Malawi' => 'MW',
        'Malaysia' => 'MY',
        'Maldives' => 'MV',
        'Mali' => 'ML',
        'Malta' => 'MT',
        'Marshall Islands' => 'MH',
        'Mauritania' => 'MR',
        'Mauritius' => 'MU',
        'Mayotte' => 'YT',
        'Mexico' => 'MX',
        'Micronesia' => 'FM',
        'Moldova' => 'MD',
        'Monaco' => 'MC',
        'Mongolia' => 'MN',
        'Montenegro' => 'ME',
        'Montserrat' => 'MS',
        'Morocco' => 'MA',
        'Mozambique' => 'MZ',
        'Myanmar' => 'MM',
        'Namibia' => 'NA',
        'Nauru' => 'NR',
        'Nepal' => 'NP',
        'Netherlands' => 'NL',
        'New Caledonia' => 'NC',
        'New Zealand' => 'NZ',
        'Nicaragua' => 'NI',
        'Niger' => 'NE',
        'Nigeria' => 'NG',
        'Niue' => 'NU',
        'Norfolk Island' => 'NF',
        'North Korea' => 'KP',
        'Northern Mariana Islands' => 'MP',
        'Norway' => 'NO',
        'Oman' => 'OM',
        'Pakistan' => 'PK',
        'Palau' => 'PW',
        'Palestinian Territory' => 'PS',
        'Panama' => 'PA',
        'Papua New Guinea' => 'PG',
        'Paraguay' => 'PY',
        'Peru' => 'PE',
        'Philippines' => 'PH',
        'Pitcairn' => 'PN',
        'Poland' => 'PL',
        'Portugal' => 'PT',
        'Puerto Rico' => 'PR',
        'Qatar' => 'QA',
        'Republic of the Congo' => 'CG',
        'Reunion' => 'RE',
        'Romania' => 'RO',
        'Russia' => 'RU',
        'Rwanda' => 'RW',
        'Saint Barthelemy' => 'BL',
        'Saint Helena' => 'SH',
        'Saint Kitts and Nevis' => 'KN',
        'Saint Lucia' => 'LC',
        'Saint Martin' => 'MF',
        'Saint Pierre and Miquelon' => 'PM',
        'Saint Vincent and the Grenadines' => 'VC',
        'Samoa' => 'WS',
        'San Marino' => 'SM',
        'Sao Tome and Principe' => 'ST',
        'Saudi Arabia' => 'SA',
        'Senegal' => 'SN',
        'Serbia' => 'RS',
        'Seychelles' => 'SC',
        'Sierra Leone' => 'SL',
        'Singapore' => 'SG',
        'Sint Maarten' => 'SX',
        'Slovakia' => 'SK',
        'Slovenia' => 'SI',
        'Solomon Islands' => 'SB',
        'Somalia' => 'SO',
        'South Africa' => 'ZA',
        'South Korea' => 'KR',
        'South Sudan' => 'SS',
        'Spain' => 'ES',
        'Sri Lanka' => 'LK',
        'Sudan' => 'SD',
        'Suriname' => 'SR',
        'Svalbard and Jan Mayen' => 'SJ',
        'Swaziland' => 'SZ',
        'Sweden' => 'SE',
        'Switzerland' => 'CH',
        'Syria' => 'SY',
        'Taiwan' => 'TW',
        'Tajikistan' => 'TJ',
        'Tanzania' => 'TZ',
        'Thailand' => 'TH',
        'Togo' => 'TG',
        'Tokelau' => 'TK',
        'Tonga' => 'TO',
        'Trinidad and Tobago' => 'TT',
        'Tunisia' => 'TN',
        'Turkey' => 'TR',
        'Turkmenistan' => 'TM',
        'Turks and Caicos Islands' => 'TC',
        'Tuvalu' => 'TV',
        'U.S. Virgin Islands' => 'VI',
        'Uganda' => 'UG',
        'Ukraine' => 'UA',
        'United Arab Emirates' => 'AE',
        'United Kingdom' => 'GB',
        'United States' => 'US',
        'Uruguay' => 'UY',
        'Uzbekistan' => 'UZ',
        'Vanuatu' => 'VU',
        'Vatican' => 'VA',
        'Venezuela' => 'VE',
        'Vietnam' => 'VN',
        'Wallis and Futuna' => 'WF',
        'Western Sahara' => 'EH',
        'Yemen' => 'YE',
        'Zambia' => 'ZM',
        'Zimbabwe' => 'ZW',
        
        // French names => Code
        'Afghanistan' => 'AF',
        'Albanie' => 'AL',
        'Algérie' => 'DZ',
        'Samoa américaines' => 'AS',
        'Andorre' => 'AD',
        'Angola' => 'AO',
        'Anguilla' => 'AI',
        'Antarctique' => 'AQ',
        'Antigua-et-Barbuda' => 'AG',
        'Argentine' => 'AR',
        'Arménie' => 'AM',
        'Aruba' => 'AW',
        'Australie' => 'AU',
        'Autriche' => 'AT',
        'Azerbaïdjan' => 'AZ',
        'Bahamas' => 'BS',
        'Bahreïn' => 'BH',
        'Bangladesh' => 'BD',
        'Barbade' => 'BB',
        'Biélorussie' => 'BY',
        'Belgique' => 'BE',
        'Belize' => 'BZ',
        'Bénin' => 'BJ',
        'Bermudes' => 'BM',
        'Bhoutan' => 'BT',
        'Bolivie' => 'BO',
        'Bosnie-Herzégovine' => 'BA',
        'Botswana' => 'BW',
        'Brésil' => 'BR',
        'Territoire britannique de l\'océan Indien' => 'IO',
        'Îles Vierges britanniques' => 'VG',
        'Brunei' => 'BN',
        'Bulgarie' => 'BG',
        'Burkina Faso' => 'BF',
        'Burundi' => 'BI',
        'Cambodge' => 'KH',
        'Cameroun' => 'CM',
        'Canada' => 'CA',
        'Cap-Vert' => 'CV',
        'Îles Caïmans' => 'KY',
        'République centrafricaine' => 'CF',
        'Tchad' => 'TD',
        'Chili' => 'CL',
        'Chine' => 'CN',
        'Île Christmas' => 'CX',
        'Îles Cocos' => 'CC',
        'Colombie' => 'CO',
        'Comores' => 'KM',
        'Îles Cook' => 'CK',
        'Costa Rica' => 'CR',
        'Croatie' => 'HR',
        'Cuba' => 'CU',
        'Curaçao' => 'CW',
        'Chypre' => 'CY',
        'République tchèque' => 'CZ',
        'République démocratique du Congo' => 'CD',
        'Danemark' => 'DK',
        'Djibouti' => 'DJ',
        'Dominique' => 'DM',
        'République dominicaine' => 'DO',
        'Timor oriental' => 'TL',
        'Équateur' => 'EC',
        'Égypte' => 'EG',
        'Salvador' => 'SV',
        'Guinée équatoriale' => 'GQ',
        'Érythrée' => 'ER',
        'Estonie' => 'EE',
        'Éthiopie' => 'ET',
        'Îles Falkland' => 'FK',
        'Îles Féroé' => 'FO',
        'Fidji' => 'FJ',
        'Finlande' => 'FI',
        'France' => 'FR',
        'Polynésie française' => 'PF',
        'Gabon' => 'GA',
        'Gambie' => 'GM',
        'Géorgie' => 'GE',
        'Allemagne' => 'DE',
        'Ghana' => 'GH',
        'Gibraltar' => 'GI',
        'Grèce' => 'GR',
        'Groenland' => 'GL',
        'Grenade' => 'GD',
        'Guam' => 'GU',
        'Guatemala' => 'GT',
        'Guernesey' => 'GG',
        'Guinée' => 'GN',
        'Guinée-Bissau' => 'GW',
        'Guyana' => 'GY',
        'Haïti' => 'HT',
        'Honduras' => 'HN',
        'Hong Kong' => 'HK',
        'Hongrie' => 'HU',
        'Islande' => 'IS',
        'Inde' => 'IN',
        'Indonésie' => 'ID',
        'Iran' => 'IR',
        'Irak' => 'IQ',
        'Irlande' => 'IE',
        'Île de Man' => 'IM',
        'Israël' => 'IL',
        'Italie' => 'IT',
        'Côte d\'Ivoire' => 'CI',
        'Jamaïque' => 'JM',
        'Japon' => 'JP',
        'Jersey' => 'JE',
        'Jordanie' => 'JO',
        'Kazakhstan' => 'KZ',
        'Kenya' => 'KE',
        'Kiribati' => 'KI',
        'Kosovo' => 'XK',
        'Koweït' => 'KW',
        'Kirghizistan' => 'KG',
        'Laos' => 'LA',
        'Lettonie' => 'LV',
        'Liban' => 'LB',
        'Lesotho' => 'LS',
        'Libéria' => 'LR',
        'Libye' => 'LY',
        'Liechtenstein' => 'LI',
        'Lituanie' => 'LT',
        'Luxembourg' => 'LU',
        'Macao' => 'MO',
        'Macédoine' => 'MK',
        'Madagascar' => 'MG',
        'Malawi' => 'MW',
        'Malaisie' => 'MY',
        'Maldives' => 'MV',
        'Mali' => 'ML',
        'Malte' => 'MT',
        'Îles Marshall' => 'MH',
        'Mauritanie' => 'MR',
        'Maurice' => 'MU',
        'Mayotte' => 'YT',
        'Mexique' => 'MX',
        'Micronésie' => 'FM',
        'Moldavie' => 'MD',
        'Monaco' => 'MC',
        'Mongolie' => 'MN',
        'Monténégro' => 'ME',
        'Montserrat' => 'MS',
        'Maroc' => 'MA',
        'Mozambique' => 'MZ',
        'Birmanie' => 'MM',
        'Namibie' => 'NA',
        'Nauru' => 'NR',
        'Népal' => 'NP',
        'Pays-Bas' => 'NL',
        'Nouvelle-Calédonie' => 'NC',
        'Nouvelle-Zélande' => 'NZ',
        'Nicaragua' => 'NI',
        'Niger' => 'NE',
        'Nigéria' => 'NG',
        'Niue' => 'NU',
        'Île Norfolk' => 'NF',
        'Corée du Nord' => 'KP',
        'Îles Mariannes du Nord' => 'MP',
        'Norvège' => 'NO',
        'Oman' => 'OM',
        'Pakistan' => 'PK',
        'Palaos' => 'PW',
        'Territoire palestinien' => 'PS',
        'Panama' => 'PA',
        'Papouasie-Nouvelle-Guinée' => 'PG',
        'Paraguay' => 'PY',
        'Pérou' => 'PE',
        'Philippines' => 'PH',
        'Pitcairn' => 'PN',
        'Pologne' => 'PL',
        'Portugal' => 'PT',
        'Porto Rico' => 'PR',
        'Qatar' => 'QA',
        'République du Congo' => 'CG',
        'Réunion' => 'RE',
        'Roumanie' => 'RO',
        'Russie' => 'RU',
        'Rwanda' => 'RW',
        'Saint-Barthélemy' => 'BL',
        'Sainte-Hélène' => 'SH',
        'Saint-Christophe-et-Niévès' => 'KN',
        'Sainte-Lucie' => 'LC',
        'Saint-Martin' => 'MF',
        'Saint-Pierre-et-Miquelon' => 'PM',
        'Saint-Vincent-et-les-Grenadines' => 'VC',
        'Samoa' => 'WS',
        'Saint-Marin' => 'SM',
        'Sao Tomé-et-Principe' => 'ST',
        'Arabie saoudite' => 'SA',
        'Sénégal' => 'SN',
        'Serbie' => 'RS',
        'Seychelles' => 'SC',
        'Sierra Leone' => 'SL',
        'Singapour' => 'SG',
        'Saint-Martin' => 'SX',
        'Slovaquie' => 'SK',
        'Slovénie' => 'SI',
        'Îles Salomon' => 'SB',
        'Somalie' => 'SO',
        'Afrique du Sud' => 'ZA',
        'Corée du Sud' => 'KR',
        'Soudan du Sud' => 'SS',
        'Espagne' => 'ES',
        'Sri Lanka' => 'LK',
        'Soudan' => 'SD',
        'Suriname' => 'SR',
        'Svalbard et Jan Mayen' => 'SJ',
        'Swaziland' => 'SZ',
        'Suède' => 'SE',
        'Suisse' => 'CH',
        'Syrie' => 'SY',
        'Taïwan' => 'TW',
        'Tadjikistan' => 'TJ',
        'Tanzanie' => 'TZ',
        'Thaïlande' => 'TH',
        'Togo' => 'TG',
        'Tokelau' => 'TK',
        'Tonga' => 'TO',
        'Trinité-et-Tobago' => 'TT',
        'Tunisie' => 'TN',
        'Turquie' => 'TR',
        'Turkménistan' => 'TM',
        'Îles Turques-et-Caïques' => 'TC',
        'Tuvalu' => 'TV',
        'Îles Vierges des États-Unis' => 'VI',
        'Ouganda' => 'UG',
        'Ukraine' => 'UA',
        'Émirats arabes unis' => 'AE',
        'Royaume-Uni' => 'GB',
        'États-Unis' => 'US',
        'Uruguay' => 'UY',
        'Ouzbékistan' => 'UZ',
        'Vanuatu' => 'VU',
        'Vatican' => 'VA',
        'Venezuela' => 'VE',
        'Viêt Nam' => 'VN',
        'Wallis-et-Futuna' => 'WF',
        'Sahara occidental' => 'EH',
        'Yémen' => 'YE',
        'Zambie' => 'ZM',
        'Zimbabwe' => 'ZW',
    
    ];

    public const STATIC_CITIES = 
    [
        'France' => ['Paris', 'Lyon', 'Marseille', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg', 'Montpellier', 'Bordeaux', 'Lille'],
        'United States' => ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose'],
        'Canada' => ['Toronto', 'Montreal', 'Vancouver', 'Calgary', 'Edmonton', 'Ottawa', 'Winnipeg', 'Quebec City', 'Hamilton', 'Kitchener'],
        'United Kingdom' => ['London', 'Birmingham', 'Manchester', 'Liverpool', 'Bristol', 'Sheffield', 'Leeds', 'Edinburgh', 'Glasgow', 'Cardiff'],
        'Germany' => ['Berlin', 'Hamburg', 'Munich', 'Cologne', 'Frankfurt', 'Stuttgart', 'Düsseldorf', 'Dortmund', 'Essen', 'Leipzig'],
        'Morocco' => [
            'Casablanca',
            'Rabat',
            'Fès',
            'Marrakech',
            'Agadir',
            'Tanger',
            'Meknès',
            'Oujda',
            'Kénitra',
            'Tétouan',
            'Safi',
            'Mohammédia',
            'El Jadida',
            'Nador',
            'Béni Mellal',
            'Khouribga',
            'Settat',
            'Taza',
            'Al Hoceïma',
            'Larache',
            'Ksar El Kebir',
            'Berrechid',
            'Taourirt',
            'Errachidia',
            'Taroudant',
            'Ouarzazate',
            'Sidi Kacem',
            'Tiznit',
            'Guelmim',
            'Dakhla',
            'Laâyoune',
            // Additional cities
            'Essaouira',
            'Chefchaouen',
            'Asilah',
            'Ifrane',
            'Azrou',
            'Midelt',
            'Figuig',
            'Berkane',
            'Jerada',
            'Sidi Slimane',
            'Sidi Bennour',
            'Youssoufia',
            'Skhirat',
            'Témara',
            'Aït Melloul',
            'Dar Bouazza',
            'Sidi Yahya El Gharb',
            'Beni Ansar',
            'Fnideq',
            'Martil',
            'M\'diq',
            'Bouznika',
            'Zagora',
            'Smara',
            'Boujdour',
        ],
    ];


    public static function getStaticCities(string $country){
        return self::STATIC_CITIES[$country] ?? [];
    }

    public static function getStaticCountries(){
        return self::STATIC_COUNTRIES;
    }

    public static function getStaticCode(string $country){
        return self::STATIC_COUNTRY_CODES[$country] ?? null;
    }

}